-- almost all defines in here are exported by the engine in newer versions.
-- assign only for backwards compatibility and for error testing in case those in the game are ever changed.
local E = setmetatable({}, { __index = _G, __newindex = function(t, k, val)
    local cur = rawget(_G, k)
    if not cur then
        _G[k] = val
    elseif cur ~= val then
        debugLog("Enum value [" .. k .. "] differs, is " .. tostring(cur) ..", tried to set to " .. tostring(val))
    end
end})

-- see GameEnums.h (or DSQ.h in older code) for these

E.LR_BACKDROP = 1 -- bg gradient is on this

E.LR_BACKGROUND_ELEMENTS3 = 14
E.LR_ELEMENTS1 = 18
E.LR_ELEMENTS2 = 19
E.LR_ELEMENTS3 = 20
E.LR_ELEMENTS4 = 21
E.LR_ELEMENTS5 = 22
E.LR_ELEMENTS6 = 23
E.LR_ELEMENTS7 = 24
E.LR_ELEMENTS8 = 25 -- foreground 1
E.LR_ELEMENTS9 = 26 -- foreground 2
E.LR_ELEMENTS10 = 27 -- parallax start
E.LR_ELEMENTS11 = 28
E.LR_ELEMENTS12 = 29
E.LR_ELEMENTS13 = 30 -- this is the dark layer!
E.LR_ELEMENTS14 = 31
E.LR_ELEMENTS15 = 32
E.LR_ELEMENTS16 = 33 -- parallax end

E.LR_ENTITIES_MINUS3 = 36
E.LR_ENTITIES_MINUS2 = 37
E.LR_ENTITIES00 = 38
E.LR_ENTITIES0 = 39
E.LR_ENTITIES = 40
E.LR_ENTITIES2 = 41

E.LR_PARTICLES = 47
E.LR_PARTICLES2 = 48
E.LR_FOREGROUND_ELEMENTS1 = 49
E.LR_FOREGROUND_ELEMENTS2 = 50
E.LR_PARTICLES_TOP = 51
E.LR_AFTER_EFFECTS = 52
E.LR_SCENE_COLOR = 53
E.LR_MENU = 54
E.LR_MENU2 = 55
E.LR_HUD = 56
E.LR_HUD2 = 57
E.LR_HUD3 = 58
E.LR_HUDUNDERLAY = 59
E.LR_MINIMAP = 60
E.LR_RECIPES = 61

E.LR_HELP = 66

E.LR_OVERLAY = 68

E.LR_SUBTITLES = 72
E.LR_PROGRESS = 73
E.LR_DEBUG_TEXT = 74
E.LR_BLACKBARS = 75

-- custom defines for easier handling
LR_PARALLAX_6 = LR_ELEMENTS10
LR_PARALLAX_5 = LR_ELEMENTS11
LR_PARALLAX_4 = LR_ELEMENTS12
LR_PARALLAX_3 = LR_ELEMENTS14
LR_PARALLAX_2 = LR_ELEMENTS15
LR_PARALLAX_1 = LR_ELEMENTS16


E.ACTION_PRIMARY = 0
E.ACTION_SECONDARY = 1
E.ACTION_ESC = 2
E.ACTION_TOGGLESCENEEDITOR = 3
E.ACTION_TOGGLEWORLDMAP = 4
E.ACTION_TOGGLEGRID = 5
E.ACTION_MENULEFT = 6
E.ACTION_MENURIGHT = 7
E.ACTION_MENUUP = 8
E.ACTION_MENUDOWN = 9
E.ACTION_PREVPAGE = 10
E.ACTION_NEXTPAGE = 11
E.ACTION_COOKFOOD = 12
E.ACTION_FOODLEFT = 13
E.ACTION_FOODRIGHT = 14
E.ACTION_FOODDROP = 15
E.ACTION_TOGGLEMENU = 16

E.ACTION_SWIMUP = 100
E.ACTION_SWIMDOWN = 101
E.ACTION_SWIMLEFT = 102
E.ACTION_SWIMRIGHT = 103

E.ACTION_SONGSLOT1 = 108
E.ACTION_SONGSLOT2 = ACTION_SONGSLOT1 + 1
E.ACTION_SONGSLOT3 = ACTION_SONGSLOT1 + 2
E.ACTION_SONGSLOT4 = ACTION_SONGSLOT1 + 3
E.ACTION_SONGSLOT5 = ACTION_SONGSLOT1 + 4
E.ACTION_SONGSLOT6 = ACTION_SONGSLOT1 + 5
E.ACTION_SONGSLOT7 = ACTION_SONGSLOT1 + 6
E.ACTION_SONGSLOT8 = ACTION_SONGSLOT1 + 7
E.ACTION_SONGSLOT9 = ACTION_SONGSLOT1 + 8
E.ACTION_SONGSLOT10 = ACTION_SONGSLOT1 + 9
E.ACTION_SONGSLOTEND = 118

E.ACTION_ROLL = 119

E.ACTION_REVERT = 121

E.ACTION_LOOK = 229

-- those added later start below:
E.ACTION_TOGGLEHELPSCREEN = 230
E.ACTION_PLACE_AVATAR = 231
